version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      - time_tracker_network
    ports:
      - 3306:3306
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - time_tracker_network
    ports:
      - 8000:8000

networks:
  time_tracker_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
